name: Build (Windows)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build (GHC ${{ matrix.ghc }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.8', '9.6', '9.4', '9.2', '9.0', '8.10', '8.8', '8.6', '8.4', '8.2', '8.0']
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: "Work around haskell/hsc2hs#81: hsc2hs-0.68.10 fails to build with GHC < 8.4"
      if:  matrix.ghc < 8.4
      run: |
        echo "constraints: any.hsc2hs < 0.68.10" > cabal.project.local
      shell: bash

    - run: cabal build
    - run: cabal haddock
    - run: cabal check
